title: AudioFilms
email: request@audiofilms.net
description: >- # this means to ignore newlines until "baseurl:"
  Listen to your favorite movies
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://audiofilms.net"
assets: "https://audiofilms.s3.amazonaws.com"

collections:
  films:
    output: true
